#!/usr/bin/env python3
"""Maintain the plain-Markdown catalog without certifying unreviewed prose."""

from __future__ import annotations

import argparse
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from datetime import date, datetime, timezone
import hashlib
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time
from typing import Any, Callable
import unicodedata
from urllib.error import HTTPError, URLError
from urllib.parse import quote, unquote, urljoin, urlsplit
from urllib.request import Request, urlopen

from markdown_it import MarkdownIt


ROOT = Path(__file__).resolve().parents[1]
PARSER = MarkdownIt("commonmark").enable("table")
KINDS = {
    "reference", "framework", "language", "tool", "service", "web",
    "release-notes", "overview", "design", "platform", "policy", "guide",
    "repository-guide", "sample-guide", "historical", "index",
}
SOURCE_OPTIONAL = {"repository-guide", "index"}
REVIEW_SCOPES = {"catalog-only", "changed-content", "retained-legacy"}
RELEASE_STATUSES = {"shipping", "beta", "mixed", "independent", "historical", "not-assessed"}
COVERAGE_DISPOSITIONS = {"existing", "alias", "retained-legacy", "excluded"}
ASSET_SUFFIXES = {".png", ".jpg", ".jpeg", ".svg", ".heic"}
PLATFORMS = ("iOS", "iPadOS", "macOS", "Mac Catalyst", "tvOS", "watchOS", "visionOS", "DriverKit")
GENERATED_NOTICE = "<!-- Generated by scripts/docs.py generate; do not edit by hand. -->"
README_START = "<!-- BEGIN GENERATED BASELINE -->"
README_END = "<!-- END GENERATED BASELINE -->"
TECHNOLOGY_CATALOG = "https://developer.apple.com/tutorials/data/documentation/technologies.json"
HIG_CATALOG = "https://developer.apple.com/tutorials/data/design/human-interface-guidelines.json"


class HeadingSlugs:
    """Preserve Unicode letters/marks and GitHub-style collision suffixes."""

    def __init__(self) -> None:
        self.seen: set[str] = set()

    def slug(self, text: str) -> str:
        base = "".join(
            character for character in text.lower()
            if character in " -_" or unicodedata.category(character)[0] in "LMN"
        ).replace(" ", "-")
        candidate = base
        suffix = 0
        while candidate in self.seen:
            suffix += 1
            candidate = f"{base}-{suffix}"
        self.seen.add(candidate)
        return candidate


def load_json(path: Path) -> dict[str, Any]:
    def unique_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"{path}: duplicate JSON key {key!r}")
            result[key] = value
        return result

    value = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique_keys)
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n", dir=path.parent, prefix=f".{path.name}.", delete=False) as stream:
            temporary = Path(stream.name)
            json.dump(value, stream, indent=2, ensure_ascii=True)
            stream.write("\n")
        temporary.chmod(path.stat().st_mode & 0o777 if path.exists() else 0o644)
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def repository_files(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=root, capture_output=True, check=True,
    )
    return sorted({
        path for path in result.stdout.decode("utf-8").split("\0")
        if path and (root / path).is_file()
    })


def text_content(token: Any) -> str:
    return "".join(
        child.content for child in token.children or []
        if child.type in {"text", "code_inline", "image"}
    )


class HTMLContent(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.anchors: set[str] = set()
        self.text: list[str] = []
        self.title: list[str] = []
        self.ignored: list[str] = []
        self.in_title = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        for key in ("id", "name") if tag == "a" else ("id",):
            if attributes.get(key):
                self.anchors.add(attributes[key] or "")
        if tag in {"script", "style", "nav", "header", "footer", "noscript"}:
            self.ignored.append(tag)
        if tag == "title":
            self.in_title = True

    def handle_endtag(self, tag: str) -> None:
        if self.ignored and tag == self.ignored[-1]:
            self.ignored.pop()
        if tag == "title":
            self.in_title = False

    def handle_data(self, data: str) -> None:
        if not self.ignored:
            self.text.append(data)
        if self.in_title:
            self.title.append(data)


def analyze_markdown(content: str) -> dict[str, Any]:
    tokens = PARSER.parse(content)
    lines = content.splitlines()
    slugger = HeadingSlugs()
    anchors: set[str] = set()
    links: list[dict[str, Any]] = []
    sources: list[str] = []
    problems: list[tuple[int, str]] = []
    headings: list[tuple[int, str]] = []
    source_heading_level: int | None = None
    literal_lines: set[int] = set()

    for index, token in enumerate(tokens):
        if token.type in {"fence", "code_block"} and token.map:
            literal_lines.update(range(*token.map))
            if token.type == "fence":
                last = re.sub(r"^\s*(?:>\s*)*", "", lines[token.map[1] - 1]).strip()
                closing = re.fullmatch(
                    re.escape(token.markup[0]) + "{" + str(len(token.markup)) + r",}\s*", last,
                )
                if not closing:
                    problems.append((token.map[0] + 1, "unclosed fenced code block"))
        if token.type == "heading_open":
            inline = tokens[index + 1]
            title = text_content(inline)
            level = int(token.tag[1:])
            headings.append((level, title))
            anchors.add(slugger.slug(title))
            if source_heading_level is not None and level <= source_heading_level:
                source_heading_level = None
            if title.lower() in {"source", "sources", "references", "primary sources", "primary source"}:
                source_heading_level = level
        if token.type in {"html_block", "html_inline"}:
            html = HTMLContent()
            html.feed(token.content)
            anchors.update(html.anchors)
        if token.type != "inline":
            continue
        children = token.children or []
        source_line = re.match(r"^Sources?\s*:", text_content(token), flags=re.IGNORECASE)
        line_number = token.map[0] + 1 if token.map else 1
        for child_index, child in enumerate(children):
            if child.type == "html_inline":
                html = HTMLContent()
                html.feed(child.content)
                anchors.update(html.anchors)
            if child.type in {"strong_open", "link_open"} and child_index:
                previous = children[child_index - 1]
                if previous.type == "text" and re.search(r"\S-\s*$", previous.content):
                    problems.append((line_number, "joined list items; put the next item on a new line"))
            if child.type not in {"link_open", "image"}:
                continue
            href = child.attrGet("href" if child.type == "link_open" else "src")
            if not href:
                continue
            links.append({"url": href, "line": line_number})
            if (source_line or source_heading_level is not None) and urlsplit(href).scheme in {"http", "https"}:
                sources.append(href)
        if token.content.lstrip().startswith("|") and "\n" in token.content:
            rows = token.content.splitlines()
            if len(rows) > 1 and all(row.strip().startswith("|") for row in rows):
                problems.append((line_number, "table-like text was not parsed as a Markdown table"))

    for number, line in enumerate(lines):
        if number not in literal_lines and re.match(r"^#{1,6}[^#\s]", line):
            problems.append((number + 1, "heading marker needs a following space"))
        if number not in literal_lines and re.match(r"^\*(?:SDK|Design) baseline:", line):
            problems.append((number + 1, "generic generation baseline; use scoped sources and metadata"))
    if not headings or headings[0][0] != 1:
        problems.append((1, "document needs a leading level-one title"))
    if sum(level == 1 for level, _ in headings) > 1:
        problems.append((1, "multiple level-one document titles"))
    return {
        "anchors": anchors, "links": links, "sources": sorted(set(sources)),
        "problems": sorted(set(problems)), "headings": headings,
        "words": len(content.split()),
    }


def valid_date(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    try:
        return date.fromisoformat(value).isoformat() == value
    except ValueError:
        return False


def relative_document_path(value: Any) -> bool:
    return (
        isinstance(value, str) and bool(value) and not Path(value).is_absolute()
        and ".." not in Path(value).parts and "\\" not in value
    )


def http_url(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    parsed = urlsplit(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def validate_metadata(root: Path, catalog: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    if catalog.get("schema_version") != 1 or not valid_date(catalog.get("as_of")):
        problems.append("catalog: expected schema_version 1 and an ISO as_of date")
    if not isinstance(catalog.get("owners"), dict) or not catalog["owners"]:
        raise ValueError("catalog: a nonempty owner dictionary is required")
    for field in ("documents", "coverage"):
        if not isinstance(catalog.get(field), list):
            raise ValueError(f"catalog: required {field} array is missing or invalid")
    owners = catalog["owners"]
    documents = catalog["documents"]
    seen_paths: set[str] = set()
    seen_ids: set[str] = set()
    canonical: dict[str, str] = {}
    for document in documents:
        path = document.get("path")
        if not relative_document_path(path):
            problems.append(f"catalog: invalid document path {path!r}")
            continue
        if path in seen_paths or document.get("id") in seen_ids:
            problems.append(f"{path}: duplicate document path or ID")
        seen_paths.add(path)
        if not isinstance(document.get("id"), str) or not document["id"]:
            problems.append(f"{path}: missing stable document ID")
        else:
            seen_ids.add(document["id"])
        if document.get("owner") not in owners:
            problems.append(f"{path}: unknown or missing primary owner")
        if document.get("kind") not in KINDS:
            problems.append(f"{path}: unknown document kind")
        if document.get("release_status") not in RELEASE_STATUSES:
            problems.append(f"{path}: explicit release-status tag is required")
        if not (root / path).is_file():
            problems.append(f"{path}: registered document does not exist")
        if not isinstance(document.get("title"), str) or not document["title"].strip():
            problems.append(f"{path}: nonempty title is required")
        platforms = document.get("platforms", [])
        if not isinstance(platforms, list) or any(platform not in PLATFORMS for platform in platforms):
            problems.append(f"{path}: platform tags must use the declared platform names")
        review = document.get("review", {})
        if review.get("scope") not in REVIEW_SCOPES or not valid_date(review.get("checked_on")):
            problems.append(f"{path}: explicit review scope and date are required")
        elif review["checked_on"] > catalog["as_of"]:
            problems.append(f"{path}: review date exceeds catalog cutoff")
        sources = document.get("sources")
        if not isinstance(sources, list) or any(not http_url(url) for url in sources):
            problems.append(f"{path}: sources must be a list of absolute HTTP(S) URLs")
            sources = []
        if not sources and document.get("kind") not in SOURCE_OPTIONAL and "alias_of" not in document:
            problems.append(f"{path}: missing metadata source")
        if path.startswith("documentation/") and sources and "alias_of" not in document:
            first_source = sources[0].rstrip("/").lower()
            if first_source in canonical:
                problems.append(f"{path}: duplicate canonical topic with {canonical[first_source]}; declare an alias")
            else:
                canonical[first_source] = path
    for document in documents:
        if "alias_of" in document and document["alias_of"] not in seen_paths:
            problems.append(f"{document['path']}: alias target is not registered")
    by_path = {document["path"]: document for document in documents}
    for document in documents:
        visited: set[str] = set()
        target = document
        while target.get("alias_of") in by_path:
            if target["path"] in visited:
                problems.append(f"{document['path']}: alias cycle")
                break
            visited.add(target["path"])
            target = by_path[target["alias_of"]]
    coverage_keys: set[tuple[str, str]] = set()
    for entry in catalog.get("coverage", []):
        key = (entry.get("scope"), entry.get("source"))
        if key in coverage_keys:
            problems.append(f"coverage: duplicate catalog topic {key}")
        coverage_keys.add(key)
        if key[0] not in {"technology", "hig"} or not http_url(key[1]):
            problems.append(f"coverage: invalid scope/source {key}")
        if entry.get("disposition") not in COVERAGE_DISPOSITIONS:
            problems.append(f"coverage: unresolved disposition for {entry.get('title')}")
        if entry.get("disposition") == "excluded":
            if not entry.get("reason"):
                problems.append(f"coverage: exclusion needs a reason for {entry.get('title')}")
            continue
        paths = entry.get("paths", [])
        if not paths:
            problems.append(f"coverage: missing local mapping for {entry.get('title')}")
        for path in paths:
            if not relative_document_path(path) or not (root / path).exists():
                problems.append(f"coverage: missing target {path}")
            elif path.endswith(".md") and path not in seen_paths:
                problems.append(f"coverage: unregistered target {path}")

    def collection(filename: str, field: str) -> dict[str, Any]:
        data = load_json(root / "metadata" / filename)
        if data.get("schema_version") != 1 or not valid_date(data.get("as_of")):
            raise ValueError(f"{filename}: schema_version 1 and an ISO as_of date are required")
        if not isinstance(data.get(field), list):
            raise ValueError(f"{filename}: required {field} array is missing or invalid")
        if data["as_of"] != catalog["as_of"]:
            problems.append(f"{filename}: snapshot cutoff differs from catalog")
        return data

    releases = collection("releases.json", "releases")
    seen_releases: set[tuple[str, str]] = set()
    for release in releases.get("releases", []):
        key = (release.get("product"), release.get("status"))
        if not isinstance(key[0], str) or not key[0].strip():
            problems.append("releases: nonempty product name is required")
        if key in seen_releases:
            problems.append(f"releases: conflicting current entries for {key}")
        seen_releases.add(key)
        if key[1] not in {"shipping", "beta", "rc"} or not release.get("version"):
            problems.append(f"releases: invalid status/version for {key}")
        for field in ("released_on", "checked_on"):
            if release.get(field) is not None and not valid_date(release[field]):
                problems.append(f"releases: invalid {field} for {key}")
            elif release.get(field) and release[field] > releases.get("as_of", ""):
                problems.append(f"releases: {field} after cutoff for {key}")
        if not http_url(release.get("source")):
            problems.append(f"releases: missing primary source for {key}")
        if not valid_date(release.get("checked_on")):
            problems.append(f"releases: checked_on is required for {key}")
        elif valid_date(release.get("released_on")) and release["checked_on"] < release["released_on"]:
            problems.append(f"releases: release was not published by the review date for {key}")

    claims = collection("claims.json", "claims")
    claim_ids: set[str] = set()
    for claim in claims.get("claims", []):
        if claim.get("id") in claim_ids or not claim.get("id"):
            problems.append("claims: missing or duplicate ID")
        claim_ids.add(claim.get("id", ""))
        if claim.get("status") not in {"verified", "announcement-only", "unverified", "superseded", "retained-legacy"}:
            problems.append(f"claims: invalid evidence status for {claim.get('id')}")
        if not http_url(claim.get("source")) or not claim.get("locator"):
            problems.append(f"claims: source and locator required for {claim.get('id')}")
        elif claim.get("status") == "verified" and urlsplit(claim["source"]).path.rstrip("/") == "/documentation":
            problems.append(f"claims: documentation homepage cannot verify {claim.get('id')}")
        if not valid_date(claim.get("checked_on")):
            problems.append(f"claims: invalid checked_on for {claim.get('id')}")
        elif claim["checked_on"] > claims["as_of"]:
            problems.append(f"claims: review after cutoff for {claim.get('id')}")
        for field in ("source_published_on", "source_updated_on"):
            value = claim.get(field)
            if value is not None and not valid_date(value):
                problems.append(f"claims: invalid {field} for {claim.get('id')}")
            elif valid_date(value) and valid_date(claim.get("checked_on")) and value > claim["checked_on"]:
                problems.append(f"claims: {field} after review for {claim.get('id')}")
        for path in claim.get("affected_paths", []):
            if path not in seen_paths:
                problems.append(f"claims: unregistered affected path {path}")

    assets = collection("assets.json", "assets")
    asset_paths: set[str] = set()
    for asset in assets.get("assets", []):
        path = asset.get("path")
        if not relative_document_path(path) or path in asset_paths:
            problems.append(f"assets: invalid or duplicate path {path!r}")
            continue
        asset_paths.add(path)
        if asset.get("owner") not in {"D", "G"}:
            problems.append(f"{path}: design or sample asset ownership is required")
        if asset.get("rights_status") not in {"unverified", "licensed", "excluded", "original"}:
            problems.append(f"{path}: invalid rights status")
        if asset.get("rights_status") == "licensed" and not asset.get("license_source"):
            problems.append(f"{path}: a licensed asset needs its license source")
        if not (root / path).is_file():
            problems.append(f"{path}: missing registered asset")
        elif hashlib.sha256((root / path).read_bytes()).hexdigest() != asset.get("sha256"):
            problems.append(f"{path}: asset content changed; review provenance before updating its hash")
    snapshots = catalog.get("source_snapshots", [])
    if not isinstance(snapshots, list):
        raise ValueError("catalog: source_snapshots must be an array")
    snapshot_urls: set[str] = set()
    for snapshot in snapshots:
        url = snapshot.get("url")
        if not http_url(url) or url in snapshot_urls:
            problems.append(f"catalog: invalid or duplicate source snapshot {url!r}")
            continue
        snapshot_urls.add(url)
        if not valid_date(snapshot.get("retrieved_on")):
            problems.append(f"catalog: invalid source retrieval date for {url}")
        for field in ("sha256", "comparison_sha256"):
            if (field == "sha256" or field in snapshot) and not re.fullmatch(r"[a-f0-9]{64}", str(snapshot.get(field, ""))):
                problems.append(f"catalog: invalid {field} for {url}")
        if snapshot.get("comparison_method") not in {None, "apple-symbol-script-cache-buster-v1"}:
            problems.append(f"catalog: unknown comparison normalization for {url}")
        for field in ("source_published_on", "human_verified_on"):
            if snapshot.get(field) is not None and not valid_date(snapshot[field]):
                problems.append(f"catalog: invalid {field} for {url}")
    for path in repository_files(root):
        if path.endswith(".md") and path not in seen_paths:
            problems.append(f"{path}: Markdown document has no catalog entry")
        if path.startswith(("figma/", "os26-liquid-glass-example/")) and Path(path).suffix.lower() in ASSET_SUFFIXES and path not in asset_paths:
            problems.append(f"{path}: asset has no provenance record")
    return problems


def check_documents(root: Path, catalog: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    analyzed: dict[str, dict[str, Any]] = {}
    actual_paths = set(repository_files(root))
    actual_directories = {parent.as_posix() for path in actual_paths for parent in Path(path).parents}
    for document in catalog["documents"]:
        path = document["path"]
        if not (root / path).is_file():
            continue
        parsed = analyze_markdown((root / path).read_text(encoding="utf-8"))
        analyzed[path] = parsed
        problems.extend(f"{path}:{line}: {message}" for line, message in parsed["problems"])
        if document["kind"] not in SOURCE_OPTIONAL and "alias_of" not in document and not parsed["sources"]:
            problems.append(f"{path}: missing rendered Source footer or Sources section")
    for path, parsed in list(analyzed.items()):
        for link in parsed["links"]:
            parsed_url = urlsplit(link["url"])
            if parsed_url.scheme or parsed_url.netloc:
                continue
            target_path = unquote(parsed_url.path)
            target = (root / path).parent / target_path if target_path else root / path
            if target_path.startswith("/"):
                problems.append(f"{path}:{link['line']}: root-relative link is not portable: {link['url']}")
                continue
            target = target.resolve()
            try:
                relative = target.relative_to(root.resolve()).as_posix()
            except ValueError:
                problems.append(f"{path}:{link['line']}: link escapes the repository: {link['url']}")
                continue
            if not target.exists():
                problems.append(f"{path}:{link['line']}: missing local target: {link['url']}")
                continue
            if (
                target.is_file() and relative not in actual_paths
                or target.is_dir() and relative not in actual_directories
            ):
                problems.append(f"{path}:{link['line']}: target is not publishable or uses incorrect case: {link['url']}")
                continue
            if target.is_dir() and (target / "README.md").exists():
                relative = (Path(relative) / "README.md").as_posix()
                target = target / "README.md"
            if parsed_url.fragment and target.suffix.lower() == ".md":
                if relative not in analyzed:
                    analyzed[relative] = analyze_markdown(target.read_text(encoding="utf-8"))
                fragment = unquote(parsed_url.fragment)
                if fragment not in analyzed[relative]["anchors"]:
                    problems.append(f"{path}:{link['line']}: missing anchor: {link['url']}")
    return problems


def check_accuracy(root: Path, catalog: dict[str, Any]) -> list[str]:
    """Check review coverage and staleness, not the truth of an attestation."""
    audit = load_json(root / "metadata/accuracy.json")
    if audit.get("schema_version") != 1 or not isinstance(audit.get("pages"), list):
        raise ValueError("accuracy.json: schema_version 1 and a pages array are required")
    problems: list[str] = []
    if audit.get("as_of") != catalog["as_of"]:
        problems.append("accuracy.json: snapshot cutoff differs from catalog")
    if audit.get("complete") is not True:
        problems.append("accuracy.json: full-body audit is incomplete")
    if not isinstance(audit.get("method"), str) or not audit["method"].strip():
        problems.append("accuracy.json: review method is required")
    try:
        recorded_at = datetime.fromisoformat(audit.get("recorded_at", ""))
        if recorded_at.tzinfo is None:
            raise ValueError("timezone required")
    except (TypeError, ValueError):
        problems.append("accuracy.json: recorded_at needs an ISO timestamp with timezone")

    def string_list(value: Any) -> bool:
        return isinstance(value, list) and all(isinstance(item, str) and item.strip() for item in value)

    if not string_list(audit.get("limitations")):
        problems.append("accuracy.json: limitations must be an explicit string array")
    expected = {document["path"] for document in catalog["documents"]}
    seen: set[str] = set()
    for page in audit["pages"]:
        if not isinstance(page, dict):
            problems.append("accuracy.json: each page review must be an object")
            continue
        path = page.get("path")
        if not isinstance(path, str) or path not in expected:
            problems.append(f"accuracy.json: unregistered reviewed path {path!r}")
            continue
        if path in seen:
            problems.append(f"{path}: duplicate full-body review")
        seen.add(path)
        if not valid_date(page.get("as_of")) or page["as_of"] > catalog["as_of"]:
            problems.append(f"{path}: review needs its own ISO cutoff no later than the catalog cutoff")
        if page.get("full_body_reviewed") is not True or page.get("status") not in {
            "verified", "corrected", "verified-qualified",
        }:
            problems.append(f"{path}: full-body review is not complete")
        if page.get("remaining_blockers") != []:
            problems.append(f"{path}: an explicit empty remaining_blockers array is required")
        if not string_list(page.get("qualifications")):
            problems.append(f"{path}: review qualifications must be an explicit string array")
        elif page.get("status") == "verified-qualified" and not page["qualifications"]:
            problems.append(f"{path}: qualified review needs its specific qualifications")
        local = (root / path).resolve()
        if not local.is_relative_to(root.resolve()) or not local.is_file():
            problems.append(f"{path}: reviewed file is missing or outside the repository")
            continue
        content = local.read_bytes()
        if hashlib.sha256(content).hexdigest() != page.get("content_sha256"):
            problems.append(f"{path}: content changed since full-body review")
        tokens = PARSER.parse(content.decode("utf-8"))
        headings = [
            text_content(tokens[index + 1])
            for index, token in enumerate(tokens) if token.type == "heading_open"
        ]
        if page.get("headings_reviewed") != headings:
            problems.append(f"{path}: review does not account for every current heading")
        examples = page.get("code_examples")
        fences = sum(token.type == "fence" for token in tokens)
        if not isinstance(examples, dict):
            problems.append(f"{path}: code-example review scope is required")
        elif (
            type(examples.get("fences_reviewed")) is not int
            or examples["fences_reviewed"] != fences
            or not isinstance(examples.get("verification"), str)
            or not examples["verification"].strip()
        ):
            problems.append(f"{path}: code-example review must account for all fences and state actual verification")
        sources = page.get("sources")
        if not isinstance(sources, list) or not sources:
            problems.append(f"{path}: full-body review needs primary or repository evidence")
            continue
        for source in sources:
            if not isinstance(source, dict):
                problems.append(f"{path}: review evidence must be an object")
                continue
            if not re.fullmatch(r"[a-f0-9]{64}", str(source.get("sha256", ""))):
                problems.append(f"{path}: review evidence needs a valid raw sha256")
            if not isinstance(source.get("locator"), str) or not source["locator"].strip():
                problems.append(f"{path}: review evidence needs a precise locator")
            if ("url" in source) == ("path" in source):
                problems.append(f"{path}: evidence needs exactly one primary URL or repository path")
            elif "url" in source:
                if not http_url(source["url"]) or not http_url(source.get("retrieval_url")):
                    problems.append(f"{path}: evidence needs canonical and retrieval HTTP(S) URLs")
            elif not relative_document_path(source["path"]):
                problems.append(f"{path}: invalid repository-evidence path")
            else:
                evidence = (root / source["path"]).resolve()
                if not evidence.is_relative_to(root.resolve()) or not evidence.is_file():
                    problems.append(f"{path}: repository evidence is missing or outside the repository")
                elif hashlib.sha256(evidence.read_bytes()).hexdigest() != source.get("sha256"):
                    problems.append(f"{path}: repository evidence changed since full-body review: {source['path']}")
    for path in sorted(expected - seen):
        problems.append(f"{path}: missing full-body review")
    return problems


def table_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def link_to(index_path: str, target: str) -> str:
    return quote(os.path.relpath(target, Path(index_path).parent), safe="/.-_")


def index_table(index_path: str, documents: list[dict[str, Any]]) -> list[str]:
    result = [
        "| Topic | Kind | Platforms tagged in page | Release status | Initial review scope |",
        "|---|---|---|---|---|",
    ]
    for document in sorted(documents, key=lambda item: item["title"].casefold()):
        label = table_cell(document["title"])
        path = link_to(index_path, document["path"])
        platforms = ", ".join(document.get("platforms", [])) or "Not indexed"
        review = document["review"]["scope"]
        if "alias_of" in document:
            review = f"Alias of `{document['alias_of']}`"
        result.append(f"| [{label}]({path}) | {document['kind']} | {platforms} | {document['release_status']} | {review} |")
    return result


def generated_indexes(catalog: dict[str, Any]) -> dict[str, str]:
    documents = [document for document in catalog["documents"] if document["kind"] != "index"]
    outputs: dict[str, str] = {}
    groups = {
        "documentation/README.md": ("Reference index", "documentation/"),
        "human-interface-guidelines/README.md": ("Human Interface Guidelines index", "human-interface-guidelines/"),
        "guides/README.md": ("Migration and readiness guides", "guides/"),
    }
    for category in ("getting-started", "foundations", "patterns", "components", "inputs", "technologies"):
        groups[f"human-interface-guidelines/{category}/README.md"] = (
            category.replace("-", " ").capitalize(), f"human-interface-guidelines/{category}/",
        )
    for path, (title, prefix) in groups.items():
        rows = [
            f"# {title}", "", GENERATED_NOTICE, "",
            f"Catalog snapshot: {human_date(catalog['as_of'])}.",
            "",
            "The review column preserves the initial catalog/changed-content pass.",
            "`metadata/accuracy.json` separately records full-body outcomes for exact page hashes.",
            "`catalog-only` verifies the topic mapping, not every statement. Platform tags are",
            "navigation aids extracted from the page, not symbol-level availability guarantees.",
            "`mixed` spans shipping and beta material; `independent` is not tied to one OS release.",
            "`not-assessed` preserves uncertainty rather than silently claiming a shipping status.",
            "See [contributor guidance](" + link_to(path, "CONTRIBUTING.md") + ").",
            "",
        ]
        selected = [document for document in documents if document["path"].startswith(prefix)]
        if path == "documentation/README.md":
            for owner, owner_title in catalog["owners"].items():
                subset = [document for document in selected if document["owner"] == owner]
                if subset:
                    rows.extend([f"## {owner_title}", ""] + index_table(path, subset) + [""])
        else:
            if path == "human-interface-guidelines/README.md":
                for category in ("getting-started", "foundations", "patterns", "components", "inputs", "technologies"):
                    rows.append(f"- [{category.replace('-', ' ').capitalize()}]({category}/README.md)")
                rows.append("")
            rows.extend(index_table(path, selected))
            rows.append("")
        outputs[path] = "\n".join(rows).rstrip() + "\n"
    return outputs


def human_date(value: str | None) -> str:
    if value is None:
        return "Not recorded"
    parsed = date.fromisoformat(value)
    return f"{parsed:%B} {parsed.day}, {parsed.year}"


def baseline_section(root: Path, catalog: dict[str, Any]) -> str:
    releases = load_json(root / "metadata/releases.json")
    lines = [
        f"**Research cutoff: {human_date(releases['as_of'])}.** This is a dated snapshot, not a live latest-version service.",
        "",
        "| Product | Version | Status | Release date |",
        "|---|---|---|---|",
    ]
    for release in releases["releases"]:
        build = f" (`{release['build']}`)" if release.get("build") else ""
        lines.append(
            f"| {release['product']} | {release['version']}{build} | {release['status']} | "
            f"[{human_date(release.get('released_on'))}]({release['source']}) |"
        )
    counts = Counter(
        document["path"].split("/")[0] for document in catalog["documents"]
        if document["kind"] != "index"
    )
    scoped = Counter(entry["scope"] for entry in catalog["coverage"])
    resolved = Counter(
        entry["scope"] for entry in catalog["coverage"]
        if entry["disposition"] in COVERAGE_DISPOSITIONS
        and (entry["disposition"] == "excluded" or all((root / path).exists() for path in entry["paths"]))
    )
    assets = load_json(root / "metadata/assets.json")
    figma_count = sum(asset["path"].startswith("figma/") for asset in assets["assets"])
    lines.extend([
        "",
        f"**Catalog scope:** {resolved['technology']}/{scoped['technology']} technology entries and "
        f"{resolved['hig']}/{scoped['hig']} indexed HIG articles have an explicit local disposition.",
        f"The repository has {counts['documentation']} reference pages (including aliases), "
        f"{counts['human-interface-guidelines']} HIG articles (including retained legacy material), "
        f"and {figma_count} cataloged Figma-directory images. Generated indexes are excluded from page counts.",
        "Coverage is not a certification of every API symbol or every sentence.",
    ])
    return "\n".join(lines)


def generated_readme(root: Path, catalog: dict[str, Any]) -> str:
    content = (root / "README.md").read_text(encoding="utf-8")
    if content.count(README_START) != 1 or content.count(README_END) != 1:
        raise ValueError("README.md needs exactly one generated baseline marker pair")
    before, remainder = content.split(README_START, 1)
    _, after = remainder.split(README_END, 1)
    return before + README_START + "\n\n" + baseline_section(root, catalog) + "\n\n" + README_END + after


def generate(root: Path, catalog: dict[str, Any], check: bool = False) -> list[str]:
    expected = generated_indexes(catalog)
    expected["README.md"] = generated_readme(root, catalog)
    problems: list[str] = []
    for path, content in expected.items():
        target = root / path
        if target.exists() and target.read_text(encoding="utf-8") == content:
            continue
        if check:
            problems.append(f"{path}: generated output is stale; run scripts/docs.py generate")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8", newline="\n")
    return problems


def register(root: Path, catalog: dict[str, Any], args: argparse.Namespace) -> None:
    path = args.path
    if not relative_document_path(path) or not (root / path).is_file() or not path.endswith(".md"):
        raise ValueError("register expects an existing repository-relative Markdown file")
    if args.owner not in catalog["owners"]:
        raise ValueError(f"unknown owner: {args.owner}")
    if any(document["path"] == path for document in catalog["documents"]):
        raise ValueError(f"already registered: {path}; edit its metadata explicitly")
    parsed = analyze_markdown((root / path).read_text(encoding="utf-8"))
    catalog["documents"].append({
        "id": path.removesuffix(".md"), "path": path,
        "title": parsed["headings"][0][1] if parsed["headings"] else Path(path).stem,
        "kind": args.kind, "owner": args.owner,
        "release_status": "not-assessed",
        "sources": args.source or parsed["sources"],
        "review": {"scope": "catalog-only", "checked_on": catalog["as_of"]},
    })
    catalog["documents"].sort(key=lambda document: document["path"])
    write_json(root / "metadata/catalog.json", catalog)


def inventory(root: Path, catalog: dict[str, Any]) -> dict[str, Any]:
    paths = repository_files(root)
    markdown = [path for path in paths if path.endswith(".md")]
    return {
        "files": len(paths), "markdown": len(markdown),
        "markdown_by_directory": dict(sorted(Counter(path.split("/")[0] if "/" in path else "." for path in markdown).items())),
        "whitespace_split_words": sum(len((root / path).read_text(encoding="utf-8").split()) for path in markdown),
        "token_count": None,
        "token_note": "No tokenizer was run; words are not a measured token count.",
        "coverage": dict(Counter(entry["scope"] for entry in catalog["coverage"])),
        "review_scopes": dict(Counter(document["review"]["scope"] for document in catalog["documents"])),
    }


def source_candidates(url: str) -> list[str]:
    parsed = urlsplit(url)
    if parsed.netloc == "developer.apple.com" and parsed.path.startswith("/documentation/") and not parsed.path.endswith((".md", ".json")):
        stem = parsed.path.rstrip("/")
        return [
            urljoin(url, stem + ".md"),
            urljoin(url, "/tutorials/data" + stem + ".json"), url,
        ]
    if parsed.netloc == "developer.apple.com" and parsed.path.startswith("/design/human-interface-guidelines"):
        return [urljoin(url, "/tutorials/data" + parsed.path.rstrip("/") + ".json"), url]
    return [url]


def source_identity(body: bytes, content_type: str) -> tuple[str, bool]:
    if content_type.startswith(("image/", "audio/", "video/")) or "application/pdf" in content_type:
        return "", bool(body)
    text = body.decode("utf-8", errors="replace")
    if "json" in content_type:
        data = json.loads(text)
        if not isinstance(data, dict):
            raise ValueError("Expected a documentation JSON object, not a scalar or array")
        metadata = data.get("metadata", {})
        if not isinstance(metadata, dict):
            raise ValueError("Expected documentation JSON metadata to be an object")
        title = metadata.get("title", data.get("title", ""))
        if not isinstance(title, str):
            raise ValueError("Expected a documentation JSON title string")
        substantive = any(data.get(key) for key in ("abstract", "primaryContentSections", "topicSections", "sections"))
        return title, substantive
    if "html" in content_type:
        html = HTMLContent()
        html.feed(text)
        visible = " ".join(html.text)
        shell = "This page requires JavaScript" in visible or len(visible.split()) < 40
        return " ".join(html.title).strip(), not shell
    tokens = PARSER.parse(text)
    title = ""
    body_words = 0
    declaration = False
    for index, token in enumerate(tokens):
        if token.type == "heading_open" and token.tag == "h1" and not title:
            title = text_content(tokens[index + 1])
        if token.type in {"fence", "code_block"} and token.content.strip():
            declaration = True
        if token.type == "inline" and (index == 0 or tokens[index - 1].type != "heading_open"):
            rendered = text_content(token)
            if "Copyright" in rendered and "Apple Inc." in rendered:
                continue
            body_words += len(rendered.split())
    return title, bool(title and (body_words >= 5 or declaration))


def comparison_hash(body: bytes, content_type: str) -> str:
    if "html" in content_type:
        # Apple's per-request symbol-script cache token changes without a page revision.
        body = re.sub(
            rb'(<script\b[^>]*\bsrc=["\']https://sfss\.cdn-apple\.com/[^"\'?]+/sf-symbol\.js)\?\d+(["\'])',
            rb"\1\2", body,
        )
    return hashlib.sha256(body).hexdigest()


def technology_entries(data: dict[str, Any]) -> dict[str, dict[str, str]]:
    if not data.get("sections") or not isinstance(data.get("references"), dict):
        raise ValueError("technology catalog has an unexpected structure")
    entries: dict[str, dict[str, str]] = {}
    for section in data["sections"]:
        for group in section.get("groups", []):
            for technology in group.get("technologies", []):
                identifier = technology["destination"]["identifier"]
                reference = data["references"][identifier]
                url = urljoin("https://developer.apple.com", reference["url"])
                entries[url] = {"title": technology["title"], "group": group["name"]}
    if not entries:
        raise ValueError("technology catalog contains no technology entries")
    return entries


def hig_entries(
    fetch: Callable[[str], dict[str, Any]],
) -> tuple[dict[str, dict[str, str]], list[str], list[dict[str, str]]]:
    pending = [HIG_CATALOG]
    visited: set[str] = set()
    entries: dict[str, dict[str, str]] = {}
    failures: list[dict[str, str]] = []
    while pending:
        url = pending.pop(0)
        if url in visited:
            continue
        visited.add(url)
        try:
            data = fetch(url)
            if "topicSections" not in data or not isinstance(data.get("references"), dict):
                raise ValueError("HIG group has an unexpected structure")
            for section in data["topicSections"]:
                for identifier in section.get("identifiers", []):
                    reference = data["references"][identifier]
                    target = urljoin("https://developer.apple.com", reference["url"])
                    if reference.get("role") == "collectionGroup":
                        target_parts = urlsplit(target)
                        if target_parts.netloc != "developer.apple.com" or not target_parts.path.startswith("/design/human-interface-guidelines/"):
                            raise ValueError(f"unexpected HIG group destination: {target}")
                        pending.append(urljoin(target, "/tutorials/data" + target_parts.path + ".json"))
                    elif reference.get("kind") == "article":
                        entries[target] = {"title": reference["title"]}
        except (OSError, ValueError, KeyError, TypeError) as error:
            failures.append({"url": url, "error": str(error)})
    return entries, sorted(visited), failures


def fetch_catalog_json(url: str) -> dict[str, Any]:
    for attempt in range(3):
        try:
            request = Request(url, headers={"User-Agent": "apple-os-documentation-catalog-check/1.0"})
            with urlopen(request, timeout=25) as response:
                body = response.read(4 * 1024 * 1024 + 1)
            if len(body) > 4 * 1024 * 1024:
                raise ValueError(f"catalog exceeds the 4 MiB response limit: {url}")
            data = json.loads(body)
            if not isinstance(data, dict):
                raise ValueError(f"expected a catalog object: {url}")
            return data
        except HTTPError as error:
            if error.code not in {429, 500, 502, 503, 504} or attempt == 2:
                raise
            time.sleep(2 ** (attempt + 1))
        except (URLError, TimeoutError):
            if attempt == 2:
                raise
            time.sleep(2 ** (attempt + 1))
    raise RuntimeError("catalog retry loop exhausted")


def compare_catalogs(root: Path, catalog: dict[str, Any], args: argparse.Namespace) -> int:
    def fetch(url: str) -> dict[str, Any]:
        if args.snapshot_dir:
            name = Path(urlsplit(url).path).stem
            filename = (
                "apple-technologies.json" if url == TECHNOLOGY_CATALOG
                else "apple-hig.json" if url == HIG_CATALOG
                else f"apple-hig-{name}.json"
            )
            return load_json(args.snapshot_dir / filename)
        return fetch_catalog_json(url)

    failures: list[dict[str, str]] = []
    live: dict[str, dict[str, dict[str, str]]] = {}
    try:
        live["technology"] = technology_entries(fetch(TECHNOLOGY_CATALOG))
    except (OSError, ValueError, KeyError, TypeError) as error:
        failures.append({"url": TECHNOLOGY_CATALOG, "error": str(error)})
    live["hig"], visited, hig_failures = hig_entries(fetch)
    failures.extend(hig_failures)
    current = {
        scope: {entry["source"]: entry for entry in catalog["coverage"] if entry["scope"] == scope}
        for scope in ("technology", "hig")
    }
    changes: list[dict[str, Any]] = []
    if not failures:
        by_path = {document["path"]: document["owner"] for document in catalog["documents"]}
        for scope, entries in live.items():
            for url in sorted(entries.keys() - current[scope].keys()):
                changes.append({
                    "scope": scope, "status": "new", "url": url, **entries[url],
                    "owner": "D" if scope == "hig" else None,
                    "action": "Assign an owner and verify a dedicated page or explicit disposition.",
                })
            for url in sorted(current[scope].keys() - entries.keys()):
                old = current[scope][url]
                changes.append({
                    "scope": scope, "status": "unindexed", "url": url,
                    "title": old["title"], "paths": old["paths"],
                    "owners": sorted({by_path[path] for path in old["paths"] if path in by_path}),
                    "action": "Review for move or retained legacy status; index absence is not deprecation.",
                })
            for url in sorted(entries.keys() & current[scope].keys()):
                if entries[url]["title"] != current[scope][url]["title"]:
                    changes.append({
                        "scope": scope, "status": "renamed", "url": url,
                        "previous_title": current[scope][url]["title"], "title": entries[url]["title"],
                        "paths": current[scope][url]["paths"],
                    })
    report = {
        "schema_version": 1, "checked_at": datetime.now(timezone.utc).isoformat(),
        "catalog_cutoff": catalog["as_of"],
        "input": "saved snapshots" if args.snapshot_dir else "live primary catalogs",
        "complete": not failures,
        "counts": {scope: len(entries) for scope, entries in live.items()},
        "hig_groups_visited": visited, "access_failures": failures, "changes": changes,
        "note": "No removal comparison is made after a partial traversal. Reports never rewrite source prose or review dates.",
    }
    write_json(args.output, report)
    print(f"Catalog comparison: {len(changes)} change(s), {len(failures)} access/structure failure(s). Report: {args.output}")
    return 1 if changes or failures else 0


def probe_source(url: str, expected_title: str | None = None) -> dict[str, Any]:
    attempts: list[dict[str, Any]] = []
    for candidate in source_candidates(url):
        for retry in range(3):
            try:
                request = Request(candidate, headers={"User-Agent": "apple-os-documentation-source-check/1.0"})
                with urlopen(request, timeout=25) as response:
                    body = response.read(4 * 1024 * 1024 + 1)
                    final_url = response.url
                    content_type = response.headers.get("Content-Type", "")
                    if len(body) > 4 * 1024 * 1024:
                        return {"url": url, "status": "too-large", "retrieval_url": candidate, "attempts": attempts}
                    title, substantive = source_identity(body, content_type)
                    status = "redirected" if final_url != candidate else "retrieved"
                    if not substantive:
                        status = "shell"
                    if expected_title and title and substantive:
                        normalized = re.sub(r"[^a-z0-9]", "", title.lower())
                        expected = re.sub(r"[^a-z0-9]", "", expected_title.lower())
                        if expected and expected not in normalized and normalized not in expected:
                            status = "title-mismatch"
                    attempts.append({"url": candidate, "status": status})
                    if status in {"shell", "title-mismatch"} and candidate != source_candidates(url)[-1]:
                        break
                    return {
                        "url": url, "status": status, "retrieval_url": candidate,
                        "final_url": final_url, "title": title,
                        "sha256": hashlib.sha256(body).hexdigest(), "bytes": len(body),
                        "comparison_sha256": comparison_hash(body, content_type),
                        "retrieved_on": datetime.now(timezone.utc).isoformat(),
                        "source_published_on": None, "human_verified_on": None,
                        "attempts": attempts,
                    }
            except HTTPError as error:
                if error.code in {429, 500, 502, 503, 504} and retry < 2:
                    delay = min(int(error.headers.get("Retry-After", "2")) if error.headers.get("Retry-After", "").isdigit() else 2 ** (retry + 1), 15)
                    time.sleep(delay)
                    continue
                status = "missing" if error.code == 404 else "rate-limited" if error.code == 429 else "inaccessible"
                attempts.append({"url": candidate, "status": status, "http_status": error.code})
                break
            except (URLError, TimeoutError, OSError, ValueError) as error:
                if retry < 2:
                    time.sleep(2 ** retry)
                    continue
                attempts.append({"url": candidate, "status": "inaccessible", "error": str(error)})
                break
    return {"url": url, "status": attempts[-1]["status"], "attempts": attempts}


def check_sources(root: Path, catalog: dict[str, Any], args: argparse.Namespace) -> int:
    snapshots = catalog.get("source_snapshots", [])
    baseline = {snapshot["url"]: snapshot for snapshot in snapshots}
    if args.catalogs_only:
        urls = list(baseline)
        titles: dict[str, str] = {}
    else:
        titles = {entry["source"]: entry["title"] for entry in catalog["coverage"]}
        urls = list(dict.fromkeys(list(baseline) + [
            url for document in catalog["documents"] for url in document["sources"]
        ]))
        if getattr(args, "include_body_links", False):
            body_links = [
                link["url"]
                for document in catalog["documents"] if (root / document["path"]).is_file()
                for link in analyze_markdown((root / document["path"]).read_text(encoding="utf-8"))["links"]
                if http_url(link["url"])
            ]
            urls = list(dict.fromkeys(urls + body_links))
    if args.url:
        urls = args.url
        titles = {}
    selected = urls[args.offset:args.offset + args.max_urls]
    if not selected:
        raise ValueError("no sources selected; check the offset, catalog snapshots, or explicit URLs")
    cache = load_json(args.output) if args.output.exists() else {"results": []}
    cached = {result["url"]: result for result in cache.get("results", []) if result.get("status") in {"retrieved", "redirected"}}
    now = datetime.now(timezone.utc)

    def retrieve(url: str) -> dict[str, Any]:
        previous = cached.get(url)
        comparison_available = (
            not baseline.get(url, {}).get("comparison_sha256")
            or bool(previous and previous.get("comparison_sha256"))
        )
        if previous and not args.refresh and comparison_available:
            retrieved = datetime.fromisoformat(previous["retrieved_on"])
            if (now - retrieved).total_seconds() < 86400:
                return {**previous, "cached": True}
        return probe_source(url, titles.get(url))

    with ThreadPoolExecutor(max_workers=3) as executor:
        results = list(executor.map(retrieve, selected))
    for result in results:
        original = baseline.get(result["url"])
        if original and result.get("sha256"):
            result["raw_changed"] = result["sha256"] != original["sha256"]
            if original.get("comparison_sha256"):
                result["upstream_changed"] = result.get("comparison_sha256") != original["comparison_sha256"]
            else:
                result["upstream_changed"] = result["raw_changed"]
    remaining = len(urls) - len(selected)
    report = {
        "schema_version": 1, "checked_at": now.isoformat(),
        "scope": "catalog snapshots" if args.catalogs_only else "primary sources and body links" if getattr(args, "include_body_links", False) else "selected primary sources",
        "eligible_sources": len(urls), "requested_sources": len(selected),
        "not_requested": remaining, "complete_for_selected_scope": remaining == 0,
        "note": "Retrieval and matching titles are not human factual verification. HTTP errors and shells remain unresolved. Raw hashes are retained; comparison hashes ignore only the numeric cache token on Apple's sf-symbol.js script URL.",
        "results": results,
    }
    write_json(args.output, report)
    failures = sum(result["status"] not in {"retrieved", "redirected"} for result in results)
    drift = sum(result.get("upstream_changed", False) for result in results)
    cache_only = sum(result.get("raw_changed", False) and not result.get("upstream_changed", False) for result in results)
    print(f"Sources: {len(results)} requested, {remaining} not requested, {failures} unresolved, {drift} changed, {cache_only} cache-token-only differences. Report: {args.output}")
    return 1 if failures or drift else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    subcommands = parser.add_subparsers(dest="command", required=True)
    check = subcommands.add_parser("check", help="Validate metadata, Markdown, review hashes, local links, assets and generated output")
    check.add_argument("--skip-generated", action="store_true", help="Diagnose content before regenerating indexes")
    subcommands.add_parser("generate", help="Regenerate indexes and the README baseline")
    inventory_parser = subcommands.add_parser("inventory", help="Count actual repository files and words")
    inventory_parser.add_argument("--output", type=Path)
    registration = subcommands.add_parser("register", help="Register a new page without marking its body verified")
    registration.add_argument("path")
    registration.add_argument("--owner", required=True)
    registration.add_argument("--kind", choices=sorted(KINDS), required=True)
    registration.add_argument("--source", action="append")
    sources = subcommands.add_parser("sources", help="Produce a bounded primary-source access/drift report")
    sources.add_argument("--output", type=Path, required=True)
    sources.add_argument("--max-urls", type=int, default=30)
    sources.add_argument("--offset", type=int, default=0)
    sources.add_argument("--catalogs-only", action="store_true")
    sources.add_argument("--include-body-links", action="store_true", help="Also consider external links in parsed Markdown")
    sources.add_argument("--url", action="append")
    sources.add_argument("--refresh", action="store_true")
    catalogs = subcommands.add_parser("catalogs", help="Compare technology and fully traversed HIG catalogs")
    catalogs.add_argument("--output", type=Path, required=True)
    catalogs.add_argument("--snapshot-dir", type=Path, help="Use a saved apple-technologies/apple-hig snapshot set")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        catalog = load_json(root / "metadata/catalog.json")
        if args.command == "check":
            problems = validate_metadata(root, catalog) + check_documents(root, catalog) + check_accuracy(root, catalog)
            if not args.skip_generated:
                problems += generate(root, catalog, check=True)
            for problem in problems:
                print(problem, file=sys.stderr)
            print(f"Documentation check: {len(problems)} problem(s), {len(catalog['documents'])} registered documents.")
            return 1 if problems else 0
        if args.command == "generate":
            generate(root, catalog)
            print("Generated reference/HIG/guide indexes and the README baseline.")
        elif args.command == "register":
            register(root, catalog, args)
            print(f"Registered {args.path} with catalog-only review scope.")
        elif args.command == "inventory":
            result = inventory(root, catalog)
            if args.output:
                write_json(args.output, result)
            else:
                print(json.dumps(result, indent=2))
        elif args.command == "sources":
            if args.max_urls < 1 or args.offset < 0:
                raise ValueError("max-urls must be positive and offset cannot be negative")
            return check_sources(root, catalog, args)
        elif args.command == "catalogs":
            return compare_catalogs(root, catalog, args)
    except (OSError, ValueError, KeyError, TypeError, subprocess.CalledProcessError) as error:
        print(f"Documentation maintenance failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
